FROM node:8

# Create app directory
WORKDIR /usr/src/app

ENV PORT 8081
ENV SSL false

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available 
COPY package*.json ./
COPY tsconfig.json ./
COPY webpack.config.js ./

RUN npm install

EXPOSE 8000

CMD npm run dev-start